services:
  - type: web
    name: hipoteses-validas
    runtime: static
    repo: https://github.com/lpcosta18/hipoteses-validas-site
    branch: main
    buildCommand: ""
    staticPublishPath: . # A raiz do projeto
    headers:
      - path: /**
        name: Cache-Control
        value: no-cache